kind: Service
apiVersion: v1
metadata:
  name: spark-master-headless
  namespace: bigdata
spec:
  selector:
    name: spark-master
    app: spark-app 
  ports:
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  namespace: bigdata
  name: spark-master
spec:
  selector:
    name: spark-master
    app: spark-app 
  type: NodePort
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
      nodePort: 8080
