kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master-deployment
  namespace: bigdata
  labels:
    name: spark-master
    app: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spark-master
      app: spark-app
  template:
    metadata:
      labels:
        name: spark-master
        app: spark-app
    spec:
      hostname: spark-master-hostname
      subdomain: spark-master-headless
      nodeName: node09
      containers:
        - name: spark-master
          image: winjay/spark:3.0.1
          imagePullPolicy: IfNotPresent
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            limits:
              memory: 5000Mi
            requests:
              memory: 3000Mi
              cpu: 2000m
